# This is a config for E2B sandbox template.
# You can use template ID (7jys74b8db8p4ksbtb9d) or template name (nextjs-shadcn-v1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nextjs-shadcn-v1") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-shadcn-v1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-shadcn-v1')

team_id = "4a542cc1-b49a-459d-bee6-f83929e963e6"
dockerfile = "lib/e2b/templates/nextjs-shadcn.e2b.Dockerfile"
template_name = "nextjs-shadcn-v1"
template_id = "7jys74b8db8p4ksbtb9d"
